import { Inter } from 'next/font/google'
import './globals.css'
import BackgroundImg from '@/components/backgroundImg'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Netflix-Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <BackgroundImg/>
          <div className="overlap">
            <Header/>
            {children}
            <Footer/>
          </div>
      </body>
    </html>
  )
}
